[phases.setup]
nixPkgs = ["php", "composer", "mysql-client"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction",
  "php artisan package:discover --ansi"
]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan view:clear"
]

[phases.start]
cmds = [
  "php artisan migrate --force --verbose",
  "php artisan db:seed --class=RoleSeeder --force",
  "php artisan db:seed --class=UserSeeder --force",
  "frankenphp php-server -r public -l 0.0.0.0:$PORT"
]
